# Generated by Django 4.2.4 on 2023-09-08 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_remove_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='aphone_no',
        ),
    ]
