# Generated by Django 4.2.5 on 2024-02-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_delete_bookcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_books_rented',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
