# Generated by Django 3.2.16 on 2024-03-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisherapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewcustomer',
            name='subscriber',
        ),
        migrations.AddField(
            model_name='viewcustomer',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viewcustomer',
            name='sub',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='viewcustomer',
            name='order',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='viewcustomer',
            name='rent',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
