# Generated by Django 4.2.4 on 2023-09-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='books/')),
                ('title', models.CharField(max_length=200)),
                ('author_name', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
