# Generated by Django 4.2.4 on 2023-09-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_rename_book_addbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='picture',
            field=models.ImageField(upload_to='books'),
        ),
    ]
