# Generated by Django 4.2.4 on 2023-09-12 07:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libraryapp', '0007_rename_whishlist_wishlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='cart',
        ),
    ]
