# Generated by Django 4.2.4 on 2023-09-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0011_bookcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('author_name', models.CharField(max_length=255)),
                ('page_number', models.PositiveIntegerField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='pdf_covers/')),
            ],
        ),
    ]
