# Generated by Django 4.2.4 on 2023-09-18 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0015_addbook_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapp.bookcategory'),
        ),
        migrations.AddField(
            model_name='pdfbook',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapp.bookcategory'),
        ),
    ]
