# Generated by Django 4.2.4 on 2023-09-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0016_audiobook_category_pdfbook_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbook',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
