# Generated by Django 4.2.4 on 2023-09-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0017_addbook_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
