# Generated by Django 4.2.4 on 2023-09-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0018_bookcart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcart',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
