# Generated by Django 4.2.4 on 2023-09-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0021_wishlist_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addbook',
            name='category',
        ),
        migrations.AddField(
            model_name='addbook',
            name='category',
            field=models.ManyToManyField(null=True, to='libraryapp.bookcategory'),
        ),
    ]
