# Generated by Django 4.2.5 on 2023-09-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0022_remove_addbook_category_addbook_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookcart',
            old_name='total',
            new_name='stock_total',
        ),
        migrations.AddField(
            model_name='bookcart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
