# Generated by Django 4.2.5 on 2023-09-28 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libraryapp', '0023_rename_total_bookcart_stock_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcart',
            name='total_price',
        ),
        migrations.CreateModel(
            name='On_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(default='123', max_length=30, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_id', models.CharField(default='123', max_length=30, null=True)),
                ('status', models.BooleanField(default=False)),
                ('booking_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookdata_id', to='libraryapp.bookcart')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
