# Generated by Django 4.2.5 on 2023-09-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0024_remove_bookcart_total_price_on_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcart',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
