# Generated by Django 4.2.5 on 2023-09-28 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0025_bookcart_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcart',
            name='status',
        ),
        migrations.RemoveField(
            model_name='on_payment',
            name='booking_id',
        ),
    ]
