# Generated by Django 4.2.5 on 2023-09-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0026_remove_bookcart_status_remove_on_payment_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='category',
            field=models.ManyToManyField(to='libraryapp.bookcategory'),
        ),
    ]
