# Generated by Django 4.2.5 on 2023-10-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0027_alter_addbook_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcart',
            name='cartstock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
