# Generated by Django 4.2.5 on 2023-10-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0029_alter_wishlist_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcart',
            name='cartstock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
