# Generated by Django 4.2.5 on 2023-10-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0030_alter_bookcart_cartstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
