# Generated by Django 4.2.5 on 2023-10-04 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0031_alter_addbook_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcart',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='libraryapp.on_payment'),
        ),
    ]
