# Generated by Django 4.2.5 on 2023-10-04 04:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0032_bookcart_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='on_payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='on_payment',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='on_payment',
            name='status',
        ),
        migrations.AddField(
            model_name='on_payment',
            name='book',
            field=models.ManyToManyField(to='libraryapp.addbook'),
        ),
        migrations.AddField(
            model_name='on_payment',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='on_payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='on_payment',
            name='razorpay_order_id',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
