# Generated by Django 4.2.5 on 2023-10-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0034_paymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
