# Generated by Django 4.2.5 on 2023-10-04 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0035_paymenthistory_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcart',
            name='payment',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapp.bookcart'),
        ),
    ]
