# Generated by Django 4.2.5 on 2023-10-04 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libraryapp', '0036_remove_bookcart_payment_paymenthistory_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='items',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='total_price',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapp.addbook'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='cartstock',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='stock_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
