# Generated by Django 4.2.5 on 2023-10-05 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0038_paymenthistory_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='total_amount',
        ),
    ]
