# Generated by Django 4.2.5 on 2023-10-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0039_remove_paymenthistory_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='book',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='book',
            field=models.ManyToManyField(null=True, to='libraryapp.addbook'),
        ),
    ]
