# Generated by Django 4.2.5 on 2023-10-05 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0042_remove_on_payment_book_on_payment_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='book',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='bookpayment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapp.on_payment'),
        ),
    ]
