# Generated by Django 4.2.5 on 2023-10-05 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0044_remove_paymenthistory_bookpayment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='on_payment',
            name='book',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='book_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapp.on_payment'),
        ),
    ]
