# Generated by Django 4.2.5 on 2023-10-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0045_remove_on_payment_book_paymenthistory_book_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='on_payment',
            name='book',
            field=models.ManyToManyField(null=True, to='libraryapp.addbook'),
        ),
    ]
