# Generated by Django 4.2.5 on 2023-10-08 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0047_remove_on_payment_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfbook',
            old_name='book_name',
            new_name='title',
        ),
    ]
