# Generated by Django 4.2.5 on 2023-10-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0048_rename_book_name_pdfbook_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiobook',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pdfbook',
            name='category',
        ),
        migrations.AddField(
            model_name='audiobook',
            name='category',
            field=models.ManyToManyField(to='libraryapp.bookcategory'),
        ),
        migrations.AddField(
            model_name='pdfbook',
            name='category',
            field=models.ManyToManyField(to='libraryapp.bookcategory'),
        ),
    ]
