# Generated by Django 4.2.5 on 2024-01-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0050_rentalrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalrequest',
            name='borrow_date',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='return_date',
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='total',
            field=models.PositiveIntegerField(default=12),
            preserve_default=False,
        ),
    ]
