# Generated by Django 4.2.5 on 2024-02-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0052_alter_rentalrequest_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='nobook',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
