# Generated by Django 4.2.5 on 2024-02-01 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0053_rentalrequest_nobook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalrequest',
            name='nobook',
        ),
    ]
