# Generated by Django 4.2.5 on 2024-02-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0054_remove_rentalrequest_nobook'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='request_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
