# Generated by Django 4.2.5 on 2024-02-06 02:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0055_rentalrequest_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='razorpay_order_id',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
