# Generated by Django 4.2.5 on 2024-02-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0056_rentalrequest_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalrequest',
            name='razorpay_order_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
