# Generated by Django 4.2.5 on 2024-02-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0058_rentalhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalrequest',
            name='request_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('payment processing', 'PAYMENT PROCESSING'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='Rentalhistory',
        ),
    ]
