# Generated by Django 4.2.5 on 2024-02-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0060_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='nameplan',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
