# Generated by Django 4.2.5 on 2024-02-13 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0062_subscription_features_alter_subscription_nameplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
    ]
