# Generated by Django 4.2.5 on 2024-02-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0064_plansubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansubscription',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('payment processing', 'PAYMENT PROCESSING'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
