# Generated by Django 4.2.5 on 2024-02-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0065_plansubscription_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plansubscription',
            name='features',
        ),
        migrations.AddField(
            model_name='plansubscription',
            name='razorpay_order_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
