# Generated by Django 4.2.5 on 2024-02-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0066_remove_plansubscription_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plansubscription',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
