# Generated by Django 4.2.5 on 2024-02-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0068_alter_subscription_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plansubscription',
            name='startdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
