# Generated by Django 4.2.5 on 2024-02-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0069_alter_plansubscription_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansubscription',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
