# Generated by Django 4.2.5 on 2024-02-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0071_remove_plansubscription_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansubscription',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
