# Generated by Django 4.2.5 on 2024-02-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0072_plansubscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plansubscription',
            name='status',
            field=models.CharField(choices=[('expired', 'EXPIRED'), ('active', 'ACTIVE')], default='expired', max_length=20),
        ),
    ]
