# Generated by Django 4.2.5 on 2024-02-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0074_wallet'),
    ]

    operations = [
        
    ]
