# Generated by Django 4.2.5 on 2024-02-27 17:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libraryapp', '0075_remove_wallet_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='wallet',
            new_name='walletdata',
        ),
    ]
