# Generated by Django 4.2.5 on 2024-02-27 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0076_rename_wallet_walletdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletdata',
            name='duration',
        ),
    ]
