# Generated by Django 4.2.5 on 2024-02-27 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0074_walletdata'),
        ('libraryapp', '0077_remove_walletdata_duration'),
    ]

    operations = [
    ]
