# Generated by Django 4.2.5 on 2024-02-27 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libraryapp', '0079_delete_walletdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='walletdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(blank=True, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('razorpay_order_id', models.CharField(max_length=255, null=True)),
                ('request_status', models.CharField(choices=[('pending', 'Pending'), ('payment processing', 'PAYMENT PROCESSING'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
