# Generated by Django 4.2.5 on 2024-03-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0082_alter_copywalletdata_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copywalletdata',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
