# Generated by Django 4.2.5 on 2024-03-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0083_alter_copywalletdata_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copywalletdata',
            name='total',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
