# Generated by Django 4.2.5 on 2024-03-06 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0084_alter_copywalletdata_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalrequest',
            name='razorpay_order_id',
        ),
    ]
