# Generated by Django 3.2.16 on 2024-04-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0086_alter_audiobook_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
